# Generated by Django 5.1.1 on 2025-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='transaction_no',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
